motd=§c§lDEFCON SERVER §e§lV3§r | §b§ounsinkable editiondifficulty=hard
gamemode=survival
difficulty=hard
pvp=true
level-name=world
level-type=minecraft\:normal
simulation-distance=16
spawn-protection=1
view-distance=32
log-ips=true
player-idle-timeout=0
server-port=25565
online-mode=false
snooper-enabled=false
